"""Scores phonotactic generators."""

import glob
import os
import tempfile

from absl import app
from absl import flags
from absl import logging
from jinja2 import Template


MOD_DIR = flags.DEFINE_string(
  "mod_dir",
  "agentic_phonology/data/ipas",
  "Path to directory containing .mod files.",
)
PHONOTACTICS = flags.DEFINE_string(
  "phonotactics",
  None,
  "Path to phonotactic .py file generated by agentic phonology.",
)
NUM_MORPHEMES = flags.DEFINE_integer(
  "num_morphemes",
  10_000,
  "Number of morphemes to generate.",
)
SYMBOLS = flags.DEFINE_string(
  "symbols",
  "agentic_phonology/data/ipas/lm.syms",
  "Path to LM symbol table.",
)
OOV_THRESH = flags.DEFINE_float(
  "oov_thresh",
  0.1,
  "Maximum OOV proportion allowed",
)
SUFFICIENT_TRAINING = flags.DEFINE_integer(
  "sufficient_training",
  1_000,
  "Minimum amount of training data for model.",
)


RUN_PHONOTACTICS = Template(

"""
python3 "{{phonotactics}}" --num_morphemes={{num_morphemes}}
"""

)


def generate_examples():
  cmd = RUN_PHONOTACTICS.render(
    phonotactics=PHONOTACTICS.value,
    num_morphemes=NUM_MORPHEMES.value,
  )
  data = []
  data_len = 0
  for line in os.popen(cmd):
    # Since the models are built at the character level, we need to do the same
    # here.
    char_split = list("".join(line.strip().split()))
    data.append(" ".join(char_split + ["</s>"]))
    data_len += len(char_split) + 1
  return data, data_len


FARCOMPILESTRINGS = Template(
"""
farcompilestrings --symbols={{symbols}} \
                  --keep_symbols \
                  --unknown_symbol="<UNK>" \
                  "{{text}}" "{{far}}"
""".strip()
)
NGRAMPERPLEXITY = Template(

"""
ngramperplexity "{{mod}}" "{{far}}" 2>/dev/null
""".strip()

)


def score(data, data_len):
  mods = sorted(glob.glob(f"{MOD_DIR.value}/*.mod"))
  perplexities = []
  with tempfile.NamedTemporaryFile(delete_on_close=False, mode="w") as fp:
    for line in data:
      fp.write(f"{line}\n")
    far = f"{fp.name}.far"
    cmd = FARCOMPILESTRINGS.render(
      symbols=SYMBOLS.value,
      text=fp.name,
      far=far,
    )
    os.system(cmd)
    for mod in mods:
      text = mod.replace(".mod", ".txt")
      nlines = len(open(text).readlines())
      if nlines < SUFFICIENT_TRAINING.value:
        continue
      cmd = NGRAMPERPLEXITY.render(mod=mod, far=far)
      lang = mod.split("/")[-1].split(".")[0]
      oovs = 0
      perplexity = 10_000
      for line in os.popen(cmd):
        if (
            "OOVs with no probability were skipped in perplexity calculation"
            in
            line
        ):
          oovs = int(line.split()[1])
        elif "perplexity = " in line:
          perplexity = float(line.split()[-1])
      perplexities.append((perplexity, oovs, lang))
  perplexities.sort(reverse=True)
  for perplexity, oovs, lang in perplexities:
    if oovs / data_len > OOV_THRESH.value:
      continue
    print(f"{perplexity}\t{oovs/data_len}\t{lang}")


def main(unused_argv):
  data, data_len = generate_examples()
  score(data, data_len)


if __name__ == "__main__":
  flags.mark_flag_as_required("phonotactics")
  app.run(main)
